# Generated by Django 5.1.1 on 2024-10-22 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_queSale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtype',
            name='icon',
        ),
    ]
