# Generated by Django 5.1.1 on 2024-11-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_queSale', '0002_remove_itemtype_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='code',
            field=models.CharField(default='ADM', max_length=3),
            preserve_default=False,
        ),
    ]
