# Generated by Django 5.1.1 on 2024-12-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_queSale', '0003_role_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationtype',
            name='code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
