# Generated by Django 5.1.1 on 2024-12-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_queSale', '0005_populate_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identifier',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
