version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: redis-demo
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--save", "60", "1", "--appendonly", "yes"]

  backend:
    build: ./backend
    container_name: redis-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - redis

  frontend:
    build: ./frontend
    container_name: redis-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://localhost:3000
    depends_on:
      - backend

volumes:
  redis-data:
