export const _id = (index: number) => `e99f09a7-dd88-49d5-b1c8-1daf80c2d7b${index}`;

export const _times = (index: number) =>
  // 'MM/DD/AAAA'
  [
    '11/08/2023',
    '04/09/2024',
    '09/12/2023',
    '01/01/2024',
    '04/23/2024',
    '02/29/2024',
    '05/14/2024',
    '01/13/2024',
    '06/22/2024',
    '10/05/2023',
    '07/11/2024',
    '05/22/2024',
    '03/29/2024',
    '08/29/2023',
    '11/19/2023',
    '10/24/2023',
    '12/02/2023',
    '02/13/2024',
    '09/19/2023',
    '04/17/2024',
    '12/18/2023',
    '06/27/2024',
    '10/19/2023',
    '08/09/2024',
  ][index];

export const _fullName = (index: number) =>
  [
    'Billy Stoltenberg',
    'Eloise Ebert',
    'Teresa Luettgen',
    'Salvador Mayert',
    'Dr. Guadalupe Rath',
    'Kelvin Pouros',
    'Thelma Langworth',
    'Kristen Wunsch',
    'Steve Welch',
    'Brian Jacobs',
    'Lillie Schultz',
    'Mr. Conrad Spinka',
    'Charlene Krajcik',
    'Kerry Kuhlman',
    'Betty Hammes',
    'Tony Paucek PhD',
    'Sherri Davis',
    'Angel Rolfson-Kulas',
    'Dr. Lee Doyle-Grant',
    'Cheryl Romaguera',
    'Billy Braun',
    'Adam Trantow',
    'Brandon Von',
    'Willis Ankunding',
  ][index];

export const _price = (index: number) =>
  [
    35.17, 57.22, 64.78, 50.79, 9.57, 61.46, 96.73, 63.04, 33.18, 36.3, 54.42, 20.52, 62.82, 19.96,
    25.93, 70.39, 23.11, 67.23, 14.31, 31.5, 26.72, 44.8, 37.87, 75.53,
  ][index];

export const _company = (index: number) =>
  [
    'Medhurst, Moore y Franey',
    'Hahn, Homenick y Lind',
    'Larkin LLC',
    'Stamm, Larson y Mertz',
    'Spencer, Raynor y Langosh',
    'Lehner - Feeney',
    'Leuschke, Harris y Kuhlman',
    'Gutmann - Kassulke',
    'Turcotte - Runolfsson',
    'Howe - Anderson',
    'Sipes - Yost',
    'Johns - Aufderhar',
    'Schmidt LLC',
    'Smitham - Gerlach',
    'Waelchi - VonRueden',
    'Padberg - Macejkovic',
    'Lemke - Ferry',
    'Koch y Hijos',
    'Klein - Rolfson',
    'Weimann LLC',
    'White, Cassin y Goldner',
    'Mohr, Langworth y Hills',
    'Mitchell, Volkman y Prosacco',
    'Grupo Streich',
  ][index];

export const _boolean = (index: number) =>
  [
    true,
    false,
    true,
    false,
    true,
    true,
    true,
    false,
    false,
    true,
    false,
    true,
    true,
    false,
    true,
    false,
    false,
    true,
    false,
    false,
    false,
    true,
    true,
    false,
  ][index];

export const _postTitles = (index: number) =>
  [
    'Plantillas de pizarra de líderes de la industria',
    'Remolque camper inspirado en el Tesla Cybertruck para fans que no pueden esperar la camioneta',
    'Diseño de landing page para la agencia Designify',
    '✨Lo hecho, hecho está ✨',
    'El Príncipe del Rap',
    'Estudio Six Socks',
    '“Crossing Over” de Vincenzo De Cotiis exhibe una investigación sobre la contaminación',
    'Animaciones simples y atractivas en tu proyecto | Tutorial en video',
    '40 tipografías serif gratuitas para diseñadores digitales',
    'Examinando la evolución del cliente típico de diseño web',
    'A Katie Griffin le encanta crear ese arte hogareño',
    'El Sueño Americano recontado a través de gráficos ferroviarios de mediados de siglo',
    'Diseño de sistema de ilustración',
    'CarZio — App para repartidores: Inicio de sesión/Registro',
    'Cómo crear una app Jamstack serverless con Netlify, Gatsby y Fauna',
    'Tylko: organiza sin esfuerzo — Diseño 3D y de movimiento',
    'RAYO — Una identidad ampliada para festival de artes visuales',
    'Anthony Burrill y Andrew Diprose (Wired) cuentan cómo crearon la portada de enero “Change Everything”',
    'Dentro de la mente de Samuel Day',
    'Revisión de portafolio: ¿Este portafolio es demasiado creativo?',
    'Akkers van Margraten',
    'Ícono de ticket con degradado',
    '¡Aquí tienes un concepto de motocicleta de Dyson que no “apesta”!',
    'Cómo animar un SVG con border-image',
  ][index];

export const _description = (index: number) =>
  [
    'Nagasaki Lander es el nombre registrado de varias series de motos deportivas Nagasaki que comenzaron con la ABC800J de 1984',
    'La nueva gama de camisas formales está diseñada pensando en ti. Con ajustes y estilos que te harán destacar',
    'Los zapatos Andy están diseñados pensando tanto en la durabilidad como en las tendencias: la línea más elegante de zapatos y sandalias',
    'El balón de fútbol es ideal para entrenamiento y recreación',
    'Nuevo ABC 13 9370, 13.3, Core A5-8250U de 5ª gen, 8 GB RAM, 256 GB SSD, gráficos UHD, OS 10 Home, Office A & J 2016',
    'Los zapatos Andy están diseñados pensando tanto en la durabilidad como en las tendencias: la línea más elegante de zapatos y sandalias',
    'Los guantes de arquero Carbonite web están diseñados ergonómicamente para un ajuste cómodo',
    'El Apollotech B340 es un mouse inalámbrico asequible con conectividad fiable, 12 meses de batería y diseño moderno',
    'Nagasaki Lander es el nombre registrado de varias series de motos deportivas Nagasaki que comenzaron con la ABC800J de 1984',
    'El diseño del automóvil consiste en motor delantero, transmisiones tipo transaxle montadas detrás del motor y tracción en las cuatro ruedas',
    'El diseño del automóvil consiste en motor delantero, transmisiones tipo transaxle montadas detrás del motor y tracción en las cuatro ruedas',
    'El Apollotech B340 es un mouse inalámbrico asequible con conectividad fiable, 12 meses de batería y diseño moderno',
    'La nueva gama de camisas formales está diseñada pensando en ti. Con ajustes y estilos que te harán destacar',
    'La tecnología de compresión más avanzada de Boston aumenta la oxigenación muscular y estabiliza los músculos activos',
    'La nueva gama de camisas formales está diseñada pensando en ti. Con ajustes y estilos que te harán destacar',
    'Los zapatos Andy están diseñados pensando tanto en la durabilidad como en las tendencias: la línea más elegante de zapatos y sandalias',
    'Los zapatos Andy están diseñados pensando tanto en la durabilidad como en las tendencias: la línea más elegante de zapatos y sandalias',
    'La hermosa línea Apple Naturalé tiene una mezcla emocionante de ingredientes naturales. Con la bondad de ingredientes 100% naturales',
    'La tecnología de compresión más avanzada de Boston aumenta la oxigenación muscular y estabiliza los músculos activos',
    'Nuevo ABC 13 9370, 13.3, Core A5-8250U de 5ª gen, 8 GB RAM, 256 GB SSD, gráficos UHD, OS 10 Home, Office A & J 2016',
    'Nagasaki Lander es el nombre registrado de varias series de motos deportivas Nagasaki que comenzaron con la ABC800J de 1984',
    'Silla ejecutiva ergonómica tapizada en cuero negro regenerado y PVC, con asiento y respaldo acolchados para comodidad y soporte todo el día',
    'El balón de fútbol es ideal para entrenamiento y recreación',
    'El diseño del automóvil consiste en motor delantero, transmisiones tipo transaxle montadas detrás del motor y tracción en las cuatro ruedas',
  ][index];

export const _taskNames = (index: number) =>
  [
    'Preparar el informe financiero mensual',
    'Diseñar nueva campaña de marketing',
    'Analizar comentarios de clientes',
    'Actualizar contenido del sitio web',
    'Realizar investigación de mercado',
    'Desarrollar aplicación de software',
    'Organizar reunión de equipo',
    'Crear publicaciones para redes sociales',
    'Revisar plan del proyecto',
    'Implementar protocolos de seguridad',
    'Redactar documentación técnica',
    'Probar nuevas funcionalidades del producto',
    'Gestionar consultas de clientes',
    'Capacitar a nuevos empleados',
    'Coordinar logística',
    'Monitorear el rendimiento de la red',
    'Desarrollar materiales de capacitación',
    'Redactar comunicado de prensa',
    'Preparar propuesta de presupuesto',
    'Evaluar propuestas de proveedores',
    'Realizar análisis de datos',
    'Realizar aseguramiento de la calidad',
    'Planificar la logística del evento',
    'Optimizar estrategias de SEO',
  ][index];

export const _productNames = (index: number) =>
  [
    'Nike Air Force 1 NDESTRUKT',
    'Nike Space Hippie 04',
    'Nike Air Zoom Pegasus 37 A.I.R. Chaz Bear',
    'Nike Blazer Low 77 Vintage',
    'Nike ZoomX SuperRep Surge',
    'Zoom Freak 2',
    'Nike Air Max Zephyr',
    'Jordan Delta',
    'Air Jordan XXXV PF',
    'Nike Waffle Racer Crater',
    'Kyrie 7 EP Sisterhood',
    'Nike Air Zoom BB NXT',
    'Nike Air Force 1 07 LX',
    'Nike Air Force 1 Shadow SE',
    'Nike Air Zoom Tempo NEXT%',
    'Nike DBreak-Type',
    'Nike Air Max Up',
    'Nike Air Max 270 React ENG',
    'NikeCourt Royale',
    'Nike Air Zoom Pegasus 37 Premium',
    'Nike Air Zoom SuperRep',
    'NikeCourt Royale',
    'Nike React Art3mis',
    'Nike React Infinity Run Flyknit A.I.R. Chaz Bear',
  ][index];
